#!/bin/bash

#/ NAME
#/     edit bundle -- edit a password bundle
#/
#/ SYNOPSIS
#/     edit bundle name

# entry point
function main {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  readonly cfg_gandalf="$GANDALF/config/gandalf.yml"

  if [[ "$#" = 0 ]]; then
    local default_bundle="$(ryaml $cfg_gandalf bundle default)"
    if [[ -n "$default_bundle" ]]; then
      set -- "$default_bundle" "$@"
    fi
  fi

  if [[ "$#" = 0 ]]; then
    logger_fatal "missing name of secrets bundle"
    exit 1
  fi

  readonly local nm_bundle="$1"; shift
  readonly local tmp_keyring="$(mktemp -t XXXXXXXXX)"
  trap "rm -f \"$tmp_keyring\"" EXIT

  set +f
  gpg --no-default-keyring --keyring "$tmp_keyring" --import "$(keys_path)/"*
  set -f

  readonly local tmp_container="$(mktemp -d -t XXXXXXXXX)"
  readonly local tmp_buffer="$(TMPDIR="$tmp_container" mktemp -t XXXXXXXXX)"
  trap "rmdir \"$tmp_container\"; rm -f \"$tmp_keyring\" \"$tmp_buffer\"" EXIT

  git pull
  gpg -a -d "$(secrets_path)/${nm_bundle}.gpg" > "$tmp_buffer"
  "${EDITOR:-vim}" "$tmp_buffer"

  readonly local tmp_bundle="$(mktemp -t XXXXXXXXX)"
  trap "rmdir \"$tmp_container\"; rm -f \"$tmp_keyring\" \"$tmp_buffer\" \"$tmp_bundle\"" EXIT
  if gpg --yes --trust-model always --no-default-keyring --keyring "$tmp_keyring" -a -e -o "$tmp_bundle" $(recipients) "$tmp_buffer"; then
    mv -f "$tmp_bundle" "$(secrets_path)/$nm_bundle.gpg"
  fi
}

require sub "$BASH_SOURCE" "$@"
