#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  # gnupg kit for osx
  case "$(uname -s)" in
    Darwin)
      block compile dmg 'https://releases.gpgtools.org/GPG_Suite-2015.09.dmg' \
        'GPG Suite' 'Install.pkg'
      ;;
    Linux)
      pkg ensure security/gnupg21
      ;;
  esac
}

bootstrap
